import anvil.email
import anvil.users
import anvil.tables as tables
import anvil.tables.query as q
from anvil.tables import app_tables
import anvil.server

import datetime
from datetime import datetime, timezone, timedelta
import numpy as np
import pandas as pd
import requests
import http.client
import json
import os
from io import StringIO
from urllib.parse import urlparse, parse_qs, urlencode, quote
from typing import Dict, Any, Optional



from . import database 

from . import matrix_strategy 
from . import date_time
from . import auto_load_bmp



# ----------------------------- Links and Aliases -------------------------------------------------------------


API_HOST = "api.caprioletech.com"
DEFAULT_REFERER = "https://capriole.com/"
DEFAULT_ORIGIN = "https://capriole.com"
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/140.0.0.0 Safari/537.36"
)


# If you want simple metric aliases, put them here:
_METRIC_ALIASES = {
    "macro_index_btc_osc": "macro_index",
    "macro_index_osc": "macro_index",
}

# Map each metric to its current working signed URL (endpoint-bound and expiring).
# IMPORTANT: Replace the placeholder with your own fresh signed URLs captured from your browser.

# Empty Template - Fill in with your own signed URLs and replace the existing ones
# Launch web page with metric chart, open Network Inspector, copy Headers - Request URL:
# Template:

'''TIME_EXTENSION = ""
SIGNED_URLS: Dict[str, str] = {
    # Use webpage Network Inspection - copy Headers-Request URL:
    "macro_index": "",
    "demand": "" + TIME_EXTENSION,        
    "nvts": "" + TIME_EXTENSION, # Dynamic NVT
    "energy_value": "" + TIME_EXTENSION,      
    "heater": "" + TIME_EXTENSION,    
    "hodler_growth_rate": "" + TIME_EXTENSION,     
    "production_cost": "" + TIME_EXTENSION,  
    # top models: supply_delta, cdd_trend
    "top_models": "" + TIME_EXTENSION,        
    "yardstick": "" + TIME_EXTENSION,      
    
    # Treasuries (Institutional buying)
    "treasuries": "" + TIME_EXTENSION,   
          
    # Sentiment
    # spread = bullish sentiment - bearish sentiment
    "investor_sentiment": "" + TIME_EXTENSION,      
    "active_manager_sentiment": "" + TIME_EXTENSION,  
    "business_outlook": "" + TIME_EXTENSION,  
    "equity_fear_greed": "" + TIME_EXTENSION, 

    # Macro
    "equity_premium": "" + TIME_EXTENSION,
    "net_liquidity": "" + TIME_EXTENSION,
    "gold_stocks_ratio": "" + TIME_EXTENSION, 
    "insider_trades": "" + TIME_EXTENSION,  
    "market_breadth": "" + TIME_EXTENSION,  
    "sp_put_call": "" + TIME_EXTENSION,  
    "us_liquidity": "" + TIME_EXTENSION,  
    "usd_positioning": "" + TIME_EXTENSION,  
    "macro_ratios": "" + TIME_EXTENSION,      
    
    # Strategies
    "midas_gold": "",
    "spectrum": "" + TIME_EXTENSION,
    "node_strategy": "" + TIME_EXTENSION,    

    
    # ETH
    "macro_index_eth": "",
    "demand_eth": "" + TIME_EXTENSION,  
    "heater_eth": "" + TIME_EXTENSION,  
    "hodler_growth_rate_eth": "" + TIME_EXTENSION, 
    "cdd_trend_eth": "" + TIME_EXTENSION,      

    # ALTS
    "alts_speculation_index": "" + TIME_EXTENSION,  
    "alts_crypto_breadth": "" + TIME_EXTENSION,

}'''


TIME_EXTENSION = "&begin=1608768000000&end=1766534400000&countBack=1827"
SIGNED_URLS: Dict[str, str] = {
    # Use webpage Network Inspection - copy Headers-Request URL:
    "macro_index": "https://api.caprioletech.com/v1/data/macro_index_btc_osc?end=1764633600000&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21hY3JvX2luZGV4X2J0Y19vc2M~ZW5kPTE3NjQ2MzM2MDAwMDAqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwMzYxfX19XX0_&Signature=F2PLKa-drSSr905v5stMxGQZQGsTPZVHgIu~0ydYEHMhqFtaknpv8fUM4LIfFSmIhjBMRfYoetzE8aOJFeVsrcXWxJqPYr4RQox8rw-~C~mQ-AAnUqWJcc7wKp67wHqVnI6w1aeTG7EOKTQAjcpfBuZYLWolFXqUBEmI~17opZdeFb56tVsZISe9GwQLWkbEj53HuU-S-iJxxdh-hNNR~DsxDyZnOppV4GjwcKI163kvfr9Eo8UyaULLkv8gJmnd8mqyngfhZYQgYZkkBBB9HLbLuH9s1572pRxsOkkVFWsVcD6yzgfN9MsRLjle-DM0uhUTzj~FgfTp~QMe07hiZw__&Key-Pair-Id=K3TU5BJCZ0S7H3",
    "demand": "https://api.caprioletech.com/v1/data/apparent_demand_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2FwcGFyZW50X2RlbWFuZF9idGMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwMzYxfX19XX0_&Signature=tlI2T9XHMtMl3Vo07oaI2O0y-20ZGv1q7B81ZuJEP5Zeb8s5uFHk5hq9W7oOgHrmguChVzuQfnnB-P6EHWjhKalIHqxI~XlH63dnU8etwhkhr7nbNCaXc2nH~dMod41Ecju-1vrmnvchKf5KZFzdyInA2SlY~Gmo5YQX-XnLIl0BgklN2m58dKAYeJj64g-62~XO3ZLJUmnM4tqKdxahMMUSvAtB4--3VRnSNvcuXx1a5ykDCPGYxWP2kv4N15SlNhQ~KcTU69SjZkTl~FX6Birw-gkLEr6cItOEEg~VuqCHAHOdz0BzXOW3Tg815zwngS9D4f4BjXoP1jxwO3PgNw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,        
    "nvts": "https://api.caprioletech.com/v1/data/dynamic_range_nvt?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2R5bmFtaWNfcmFuZ2VfbnZ0KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=rq6uARqHerF~fWtDvJFfKPXc5zLrXb-G9dEu~D98Qj7BxR4Qf3N9QVUldz0Z~j1fB0W2CDo~U64aKg1UZ6aBpnJgkoXx0x3CMyICqankEZyA-aSavs7w3-Tf9Viat8QBjghO8KzU1x5z7Bh-iK2DpV8cCjPqEMMFS4jT~ykSlfREb5UbgjpRkXyI~2Pk6bdVlnoQtTI3jmWkpF4fYmovVXJ4xEBO1BBKwpXFbREMk4QzGKZvN6QFbhw5qHz0bbms5isy6PnMf~5h1eJFE~bu5ZZcmWSG1tekEZEukOJsvObycWhIpwVX0Wm8rDCwjtmOuVFvUvYJVZym2jRbFuFbdw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, # Dynamic NVT
    "energy_value": "https://api.caprioletech.com/v1/data/bitcoin_energy_value?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5fZW5lcmd5X3ZhbHVlKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=LlbOi2toNDKl5CcvOrc42PS2AIG7bFGVMszu6KZE7ST0SrsuFd-DqUfkM8FEzp9JmqZfdEO3vKpe9MCHUSaLGTCikbih~rImu2OubuDUx7ZDsFzYB~7lIpwOhmg3qEuqgSREb73p-PpSa39EhYy25EMCV6QDPB2R3aHipEghXayf9AVk3PeG04MQxgAEN79nO0mvmk7uyxKVBgRh9~GoPcbdnknNctMdgfPyun2lIbVM3m4HMnosDBCy7pHLJCAXjOF1fQ5MdInX1Lk79EoeZnmdZKaWb0iVqLAyoBvf9wpTWo3RZlLvRwGniD4EVHLQQ2APybA7y-~DxDuyyDW9RA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    "heater": "https://api.caprioletech.com/v1/data/heater_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hlYXRlcl9idGMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwMzYxfX19XX0_&Signature=ovRXE4-DmgX1MUjyvj4zmS-C32ofR~wLwDB1m~W6HejvYaLh3YXeJAwV261vj40zmQ85UB2bzNrJlIaDcOMzocjqUNqCvwkEa0TYzICrD73hINWlRNH3leHPWyLMxiISvYZ7krexR58elUofWO8S1g3AjgJjC8jqGLaGPWhcfXMB92bw3vpHFla42XDN97l9nnpIy78KaSzz~CuKot8zcsCL-xt~8MKs6UNdLqP5YNqXiN5cnhBPlxkqyDwDxdSs-t1l0KT2AU25Gc23tPQIjiWh~4f6UiJkOSTiVIG3ybCcJCPdOobOl2FTL-BjdjMo5ITP15Yw6MKxwYCFLHCYcA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,    
    "hodler_growth_rate": "https://api.caprioletech.com/v1/data/hodler_growth_rate_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hvZGxlcl9ncm93dGhfcmF0ZV9idGMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwMzYxfX19XX0_&Signature=YyFwDPoH3jeB2bRwBnthsI~zXcqnS5JsjHEQi-iJFb33N~btfi8VT6uKC1JsTQ-TtFucAAeOF8ApyLNS6O7~RzIug~dM87f~naaz7xLV1o0d4JWjTQJUCL-U~FX9QfThep~RAuOId9vn39nf0RS5nzswi7E4Jg6y2YPawSnJ-sqWIMPYG2U0rp50PvzUFq5YKvrvg3sBhx2iwoGoamTr0saUTVMXxSlzMHIQ-0ds13QlWUCVxcB9JHHRYCsZNpAS24vC0Gy5yTol7-5gtBsOq0e2yKCBXX4EhTjhCyxzht5DCEGG1ucFM1Jxvx7n-~fIFyw0iTFXtKdEy558p88rxg__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,     
    "production_cost": "https://api.caprioletech.com/v1/data/bitcoin_production_cost?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5fcHJvZHVjdGlvbl9jb3N0KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=o-GQtdeO1Nl12aY4dXBZIvTjHGZVtvjkAhs9P3Ad1XzeRneAv8SNz~NaV68kIccQv0lNpgLAHhbxgSIUWGqL9QHkuI7OUcCZGzdQtorrUY5iyUfXU1GHtxt-yiruG2CitbmqF8oH43VxjGS4YQC7hj2lrDUIvtFvTA02A47t9iHiI~0ypv2F5NdGdZuFzg8srJG~QLQokrpuH~DGW58~KcubJqBMSwjD6oORd9trRxHdX4icrMSemhLscUsV-lUOV0X-bwmimUeEcwE0ocBIN6jUcMDRdtz0qazKvaJhKz8bUkaMbjxpaATeKHxdbiOAJ8RdMRP3YDQlRAoxsDe5Wg__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    # top models: supply_delta, cdd_trend
    "top_models": "https://api.caprioletech.com/v1/data/top_models_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3RvcF9tb2RlbHNfYnRjKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=rIklQ7H3t4cIbAuCvRNHVCauv1A7zjK6aJTTwGMjyTHKjDFbIXS0J00ofRFv2TA0LqHMkfg8U~5vRZexb2x-Dgg5qN8SDeTrYgZA9a3EJgakxak4Y8ul-K4IzcUZbTWtihZETfFCvsKfe2K6omLJ1LYCGBpJ1rQy6NznW1lx0jeNSduMxBca-tbRkv3VuTdPhfnOinOxk7RAW9QPjKA2VTjcdhZ-4hQh2ll0IG1IUU~0exIsvmTtSiMgTzaJ~8TXwTAj1o~Pz7obmbE6LCpUCYnlYDbTgfGiOLotWyzU-lXiFscU7FCu7Bj11Zm88o4E2xRA9qj-o7qytUf3PIgt3g__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,        
    "yardstick": "https://api.caprioletech.com/v1/data/bitcoin_yardstick?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5feWFyZHN0aWNrKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=EACIi3yNRAyp6MOByffPNmC-vlZDPfHouy~Jm1cGXEF5cLT2S-rsG2hN5z5WtZL56CsQXTRWY1r1NLHbyqxZs8caPsBqhIbFwFpYmtnghMyWKmNVx~wVjrX5HpQl~SrYQy3bcUGmvW7yIbaFTiRt-mn34GI339Z8cPk5db3jBLasFhzBJlpXRSLjhVmzTmzCW45KtmHOkOSCj8Y10dRc514eN59twdHYfeN0vwgUc0U5g8lbiBw9ruBt7qvOqb2P6HZ7U7Gup0OwzsXhvrgFbxuTPPpS0mK8dlsK0eJPTrMBmU4koRNlqIaBUJWqJ3CPv--HEJN0Bxlx2T-9zIYUYw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    
    # Treasuries (Institutional buying)
    "treasuries": "https://api.caprioletech.com/v1/data/bitcoin_treasuries_aggregate?sub=Pro&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5fdHJlYXN1cmllc19hZ2dyZWdhdGU~c3ViPVBybyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NjY1MDAzNjF9fX1dfQ__&Signature=VQ0DozInlzWDOGh2DVinl4ZCm3AzQpYoFPW-F~UP19R0jmzauYUSxO~AMLiRc2mNHkpz6Z4tIPouG5w7f7fVW-G-dGTFCQCkFefIvsK1AeLBi687mKE9xWOz9jp6JT5GalvTNDOGkVBJAJJvNG9TB7UXNOAqmaaF4DnAxupMoRrGcgEsc34pAXSRh0hzLrmUMHHODbWJNaOX6cAQQRsT1-123MsCZdSRmrkhs4r1KKCbZnKVnyOXPQQRrQfupduw6W2IjCrOcnVQFXoqfazSif7vLN-TTUYu1k09Tiu0WQMXECj~8WqGqH8gOaO2-YlwkF-dQJW3uFhGqpEWKNqJmw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,   
          
    # Sentiment
    # spread = bullish sentiment - bearish sentiment
    "investor_sentiment": "https://api.caprioletech.com/v1/data/sentiment_aaii?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9hYWlpKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=M6LJMwqjgBRXA3XoEwJ5Ih7ofrxgf~cWBTI1WC-kGB0r-K9MvzNO-lh9hB4n1FAmew7bF81jMRHVB92TwPcfxoPFmORMeylJgQa1HZYeoowGRqqtbyBo3doJCUdViU2NoRTxiQbB73b0Tu7jv3WGLSomNM03buShWObI1CuPCH7dUbyNz5GCNdQrm2kpKQZyWH~NvJgQESl~cNTfuK2vEQKgkjoP2Mr9rGllPk~vyvBFsQvaUd9AXk8lmNplhezU74s3cxmoyJwVl5vCHGrpAvvCjiiuZ98LjYswUh1jDFGqmj2uppbWsg0o~~j2mrU3MvksqvhWMHwD~YLiwejkHA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    "active_manager_sentiment": "https://api.caprioletech.com/v1/data/sentiment_ams?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9hbXMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwMzYxfX19XX0_&Signature=THyFwVgNNZnRabyFbx6EkDl0ERaMhucrz9CDWf465Aa8X~5Pe~j8O3RkpuzXDzE9mO7OjGEoXdZJTqwWEdpHgAjUP3NYTnUVHP~DDoJaMSMJVgBGzK-Np-fuuJXm9~V-78hIIVHyMBIZq-FRQpXkvsTN~SJqUwpeE~em26l1QdnQuSY00cnVEcvt03d-5GwOLpIkiif7IMdd3DhEX4~QxR1XWwtI0IYuYI-1n0uMaZKfWxojI077KnI--hELxvxWRkMpcqAEMD9xIqqedbrqci5WlHQBiCLHBhwlryw4-SiNnatNrlscntnF9FbErYE7TJ3zcNQnOKqxDP2NNqYEZw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "business_outlook": "https://api.caprioletech.com/v1/data/sentiment_pf?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9wZioiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NjY1MDAzNjF9fX1dfQ__&Signature=lxz3LAoJf7aLj2Iq1pfllmY4ZwMZstgX9rzX8a6UynXhcvJ5GCa8bHYIkCHpDEVDSuz8bbzfAwhqXrz-0TFOVBy6kUKYU8WjwKX6Qly9D~5LkT6HayXwSXMwD~r-U~b52DdTipazAS4v3XVUqGRW5kN8iqG1bVN7jJ5tMoKhSvu70Vt4RlbzhPlT3RmqyKtSUlsEN5njmqIyay6Awd7Bp2nq8l4X33vDwJrPtRyROknh9JUbLWPvakGFvCuzi4Nh1zJx6yBX9SCrk6ibw9VcaqzebBvnbdZRQ5EUWYB1ajNNabwVc-3RA7qsfO17RUgp1kMN3ebzH2yDqG5w5JWE~Q__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "equity_fear_greed": "https://api.caprioletech.com/v1/data/sentiment_cnn?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9jbm4qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwMzYxfX19XX0_&Signature=UucAV7ppPBHgGukM~q5B3p~kLMvm4Jdc~Q3oXKc1t55ndwoeaDew-s5gBcTVafR~4FN4ofkXZGIJVqThnqkhHAZBu9psvJbsDhlATnFuMG0vSYot1rMmpHnycJ0j8wa~SiTIH6xgXwhVRVgqZZuwqIHZJgBd0FQM34kl2mXJGvw4qizCoGums7-ZHBw3x87nu75hxHyDHn9A2vo~xxnMGafFmNAA-wdK8KeUzBO145Y7K6evz2AtnlRnBdUW5loZjuGtMXOPLyTDjgAqo~mruq5m~n9Uj2uK8kej0kkCL5~iWPSwBPqxJGHYQaU1n1sF1dWz17I8xMrrfaIS1z2Mqw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, 

    # Macro
    "equity_premium": "https://api.caprioletech.com/v1/data/equity_premium?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2VxdWl0eV9wcmVtaXVtKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=NPtqvKNVI6g3zeWcpp3dDY4-IoMKD7JAJK6IJXpkOzFonXvGGwYmKB9yyyWjL8d3tHFraJPptfBdfMFNut337fZjSMOT8k3bZ8zrtp3L-phHrSobcIvN33yEEgLqT6fzKewiCzNlk1d1QV-JPY1kbpaPoOEbTWlX0HgskUUtQW-TqQKoPXhrRk4r9PxCcDErcWhcroauvrqVcg-kL4UQom4PCZX7FldEKJouuQVvDqhmGjXc4o81GraVKUY-VrzGmuSvMJEHipzA13Nsc4LSzudCaik4abk-PXwe-af5iFA6IoJq1c-I9BukZ5ZYyfod9ESjsUct3wc44ViID09PeQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,
    "net_liquidity": "https://api.caprioletech.com/v1/data/global_m2?sub=Pro&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2dsb2JhbF9tMj9zdWI9UHJvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=UBLHazOFSeVvMujRpxm1yVP1GyXc4d1r7CA145HHj7g~fevVNnTRQasUmHVYATcv~tOakOCZobjfn-kyFiaiVSlBpeKBsCEb0khDQTmYbmjeu4jOAuAjLCTbqQxplFqSAhZ~cCkGp9tRjD9UUZ3DU9yJ9v~rJibfS6hE2nwSgQ~IDXMOV6hQivhbXmv3gfcjE7eTFnQDuOJdOTN1MKgFqY3dGvLxmuNRspMu~-CoGZ7dPbZ9J7DtgDgWEtYNHbYY4zdPgJLtPpmSBMyuc4I7689fFcOGgVSyFYLDanZLSg9ow1EtjHHP77mGu7vM55rhQNVI3zkKjcguoiqMtUK6Ng__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,
    "gold_stocks_ratio": "https://api.caprioletech.com/v1/data/gold_stocks_ratio?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2dvbGRfc3RvY2tzX3JhdGlvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDM2MX19fV19&Signature=Cmvi1lI4mBZ8PEWYUvSlYFQZ1dmjONXNkRwIkbYPI1j9JlnqovPcSV6tLvJ1AEJ~hWBB~eJ~daRLXQVArPVq-1m96lxD1zFXwU2HrfU6LFRbpIIs5oW1-Pme9vk~SALbpXZCq29rU4AmgSRukw0Oh39LDo-bhksL~pmPLU9k2j9Na6g3EP3LjP9y~zLOrQvIEYsxpu0cWCAecC-VCdCW4yCg0P5TaJnRN9Ctr4G0e8c~Ne8pjbtkcBkUaWhOl~swTZXQu0ZrgeJG~eru7tGmM6KqkFDmMWj7pucJGxRXDee04x~P9ZImN12kL2AGtrkDZPdjIURlHNQUva6WLKU9IA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, 
    "insider_trades": "https://api.caprioletech.com/v1/data/insiders?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2luc2lkZXJzKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=bjjS0AgFVQY8V1J8nEmKS-hfA6oY-erDlvy5e9bZZ89zrCP8rRIHYRm9-fmJ-eThxv-svDtssmiPzmPZbJNRh-SMkRz-IfprT38NVMmIo8-ANrAC4R~3QRGiucK0IeJBRCnVAM5Rwm5tOfZzDnLD1upOU-1NHtFZKZc-yw8bHiClGBD5tTTDH2PGFOuCnY3r9k-fMGpOVBOPeHZQB0KMC8ypTgR8EMuuMCswNoft7Z-veVTQmrX2wE5w4x-PxaTMNy538Yvq5up~FjIgnFWli0Uw7LlV3uiN15oqKaJ42uPF0taBBuJjgBDuPLwB90eSszOhSfh01Z29brzs4JYW3g__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "market_breadth": "https://api.caprioletech.com/v1/data/market_breadth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21hcmtldF9icmVhZHRoKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=m57Olb46G-m76SXLSYY2jeGfZCP~SmCKdlCHb8tXoraUlkY4QnTrnqMM8YUOOgE~LsAdokB2znYPXETWq9D3pD3CN4X~BwW91TSqbbFN7jmFV14Pemn35VlqkR9~1uaRkERDeKtYfhgnX~7LYznRVdmVbWqRb90mvaHhx344I-X4gAcCHOIO9yrXFsKkLiWf4rJNnvfx460B2ZZ2mgFh-Sd5PwB7ti7NPlbdAq-XeeEpvnoEw7dx~lvxareDg4T5wdoeY45kUhTCeUMRSwfYHhNAgflgtxwB8xcM4fASq2NvzGVJaznEyhuvOCtZ4y~pSqkvJGjkvNlzhdASWryoXA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "sp_put_call": "https://api.caprioletech.com/v1/data/put_call?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3B1dF9jYWxsKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=si1NXvzFwMWDC5~8arfGfIf~mg2oxV6xm-A6Y8NEFGBC39Oa83pS4GByNQIb0Z4N2OeuUJoXGhYgVq8cOrPJ3hZesWnF-0NZy5FidOZ1bFeF2FRyKwR69bYmx74U0EI8v7IJ7yKsLwO2zpBJ~Tc-b-dSvGXidauKleGOM4fVulMZrDKKWHzqraXhatqNLeQVJrrJZpsxrO6CMd77UJKAVK1uWIJyunyXR4yR1HOz6MsAFhV1tAJrJCADro5oxhrac4ROfjWR8fOiHMFMNxct3MPdFbRjHY82l2NjyRPHd99IUqJo13oHBNz1A6FAzXfE1Ii3CGx7GFw0I1EAKts~9g__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "us_liquidity": "https://api.caprioletech.com/v1/data/us_liquidity?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3VzX2xpcXVpZGl0eSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NjY1MDA4ODV9fX1dfQ__&Signature=PA0ExJmhTx4KzGCVWDpzuKw5nHo7ileoja1yMvES8I5hdYTyiBYqqwB2-zdPpbiLqayXLBDR73o8ai62D~5npd-gIzPAtfx5bCWwBOjIF4qJubKr1c~SbYfFgGTCHgPhVaVWArv02mUIqNgBzciUvI2yrjhPXJDWYktmxYQmwd6EiJkoLoCKBxDYZWK3WcKImgHlydLndg1gBykNbFtbC2D6F7UhYyVLndfaZ4HlW8b6OjD~yutgqdCQvaaTrjb3yQEWEcyXGrwtZ5kvQyaNzZk0InK9~E8p3EpywHioceJ8UrXNrPJa2bqjWuuafo6h43aj-Rb7KnJiusTXovHhJQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "usd_positioning": "https://api.caprioletech.com/v1/data/usd_positioning?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3VzZF9wb3NpdGlvbmluZyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NjY1MDA4ODV9fX1dfQ__&Signature=Aw0FhYRgzyBX3q-9GQuaN-A3FIpVZ6pkQjzqbSJadyNxbSFJnK6e3yzOW5kK-e-khJQFoLDZ7JchCXs8oI32nWwqyEeuWTFEhWhCuPiQmqY4mGA0KEb-bp4LvNlUlsx~NpGXUhJrM8t9M0Az3T8M~QjN00DKrnQWeO1oCOxazGIefXDiblt4qbnXAjKI6tx5m-maU0jj3D7-ULrLNz38DSWqYS5f5F8D9m0jvnnrJo9W5Go4PLXIPGcZ4vSinkp~Es20moy-mVS~qxag-nhk-MwDs0ftjblacqIpp6g9eW32hpr9oJDPSyE9IYduPU19kQDB77v9kNrJ1-ojeeXs6Q__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "macro_ratios": "https://api.caprioletech.com/v1/data/ratio?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3JhdGlvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=aTOrsjp2zdgqKjM0kg2ewgCe9vmvN3S4GngDCuV939BKt-iRvPQ9-lPEzT6Jrge8d85~UnBNTmVNM2h9EBldiF2jMkKWZzZZkI7-fM4eb0R-5t1wKiVGiaRcKX2e1wL0osg7i7xE6rGROMy4AmcAwoNOwyWNeWyaK0jsQVbJusWSNE6lGSyLk01VrcjGYHCnIWbESt9U~ihdFLS~wY4xi2Bf-oViKbSSNS2UpI3-HQ3eFCcuUFofVwdeD7492G2XBjTrGIJret-DlA1GQTnPfMTps9udnYBLYMgvbAPC24d8qC0quroqEJm~9ySlYvR~Vzdkrr2Z~dj57M5EhU-uCw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    
    # Strategies
    "midas_gold": "https://api.caprioletech.com/v1/data/midas_gold?end=1764633600000&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21pZGFzX2dvbGQ~ZW5kPTE3NjQ2MzM2MDAwMDAqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwODg1fX19XX0_&Signature=FnhRmGOV0IpujoN7n3GT3ovIWy5sQRL2yXDi158S90o0DDSZYdxvvvOs6q7HvZ8OP0vQ4Gcd8sz1uBHlqP3qq6r3BnomEZ0m3BZzFKv7rceE0ikhkDKzPlScOvcNU4wpLD~83S~hAoaCQN1oLsIqzrExsu1H8i0SZu6ZEMvJIK6Cap2I9WNpTeAcSKLzK1c6bhQ0otQ3msYIbYSLRat1Q0nREpL6D-VL8tqPFYXjwawBz~HWp16gkkCCeY0ODeAIqdVvYrWpRhhcid1sZ-MNjAsn4bTctRLScd2~F8RmSc44oU~BOfktmAJwPff8XUezDCi0j1pkmWX3yfcy19xNjg__&Key-Pair-Id=K3TU5BJCZ0S7H3",
    "spectrum": "https://api.caprioletech.com/v1/data/spectrum_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NwZWN0cnVtX2J0YyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NjY1MDA4ODV9fX1dfQ__&Signature=M2S95lgbEaR7W8eUQgPH0ND8OqBcVaQzSsn-OeXbKd0ZsLM7labT9EQVkoTWsf~uh66WHYQnKze1CMNTXYAapD3J0Il2VR7wLqMQ7LqVXhT6DlPjuJDFD4AlxmRuKHEzjtNDbz3vJKwB~DnOKjtzVrfR7ZAdd4UWMgYpDrf7CNE3jY077ojbUWtpkvTOVGS1J~c2I9Y-~uO6PikCvwQIjZfi6-DXDU3nU7XgbZioCfHX~dRtyMIzJfO3t5gANg1vWN0hNNa1uoC3PRzfUb-SP8i~woA4ADhypIxHK5rdzbE9tYdDTDS-Di-Bhv8V3YJg0tAMa3VSNBL0IPm1p0nOBw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,
    "node_strategy": "https://api.caprioletech.com/v1/data/node_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL25vZGVfYnRjKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=JA5853YX4q-qiSXpp1hXfKoSk5cdbNMcoen0E4lS3tqTdpOx4nMGCLgsr8NNeVhX7fqRyl1otwukN9eKms2lX7b3~cIir40kfYaVQxUdgxlndRlxGy3RuoPhYy7PX85K8BCHS0EVCOJ7bC-awmTpz7ysXv43ECbUiKelHXMA8y1ypnkjHt~bPMpQsJJX2rTatUkqvg4YY5J-1AXsnHljnTkh4EyAyJTjoLM4vexkpd7keB2MWEiAmxhGoiEjQRa7qeFR6NfIgdNaI-~e2tM~dVAWiYUYPN~nuVsL4bVSMYEQNhjYfTQRweDQvKCbubGb4fl1o5ryQ7KILDjEpD7I-Q__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,    

    
    # ETH
    "macro_index_eth": "https://api.caprioletech.com/v1/data/macro_index_eth_osc?end=1764633600000&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21hY3JvX2luZGV4X2V0aF9vc2M~ZW5kPTE3NjQ2MzM2MDAwMDAqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwODg1fX19XX0_&Signature=WG9cdypEP5laJ5yGqTLCFouOARrEuqx61wepeH5CYnezdI0xOyVlpOdJINrmD5Abq-jBm5dToPk5L5Y3vJBXqTi1S9GnqFyB3p-6jkYxp27NwEdUOAnbRXdWQuEHF8in19eR3n-xucJOmziq9M4znKy-RLMveYTJ2LizzbBNdq2ysPGoNTJUIh5-fvBOZlpqtcWTFloaULozKZlQbCcYzDFIvx2Hql5yiaSgo37f4dbbVM3EGnC2Q19rpC2xN4G3zncHLpliY6OpJojBEEdIz85fLQ6lu1wgv-bV0UHSn4GW99QicpQC6OttVS3F8V6K3lDAZF7f1UUbYbzTOhYJUw__&Key-Pair-Id=K3TU5BJCZ0S7H3",
    "demand_eth": "https://api.caprioletech.com/v1/data/apparent_demand_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2FwcGFyZW50X2RlbWFuZF9ldGgqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwODg1fX19XX0_&Signature=CjNN9aV2bsGOogBFqL6m3QtxLOJGF~LJy7PzDUBiur9Ppquon0wDbYJZlFr-n5r4azP~mhJQjup~-lLp6M8WIW6LAPazwRU0kM1jta7AM63RNwWLP4dnXzBpl1BMFM7wBaQ7fo4ju5JsHYxsT4hvwP8zLejPstsIJhD~CvDXwJyW3Jb2AHWEWLIqtQhpiFrGJurV82z1BnF1TITAZBNsSl3FEHcZUFqMD13y9J8ZNEYKQoc~zXC0n2nEJ6VMwOeMzZL-5nRR8EQpwJIOVIuUbhY4b49tQsu9qWlpOBNCCegEZ5PhGY7ZSSHrrhyFGN7KSHjIL7X4hi2hON89iAViKg__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "heater_eth": "https://api.caprioletech.com/v1/data/heater_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hlYXRlcl9ldGgqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwODg1fX19XX0_&Signature=S64deMVrRx5t66OtYIXxUUbNMYHEgdQOWqGytGBZa5RbbgBLMd-de9mqPZ-cEs5xSKQ4LX7hgtrg9jJbmA1U6hquNbrOhzsL4WIqhHrSy5q8nf59vUXuBox8mQWAQ3rIovTAfwJSMBUASONo28GWI1cUPwFOcyWV5AG8zfAnnceAUgYOQ5TQMxlRgBdv4d5HeDrByYJaY6J6ToLcMgax-3nG~XCjSCOqL1dKrv1Q4Hi8emi1-gotjccoDf5e~UiVEGXHbz5O1KQvMqsg8MsOquP2hrZzVqeQn5LMd1YlYmMiR3Za-ANrhlmhzWWCEsli5Ad9oJJN~kZYAvw5A2aFkA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "hodler_growth_rate_eth": "https://api.caprioletech.com/v1/data/hodler_growth_rate_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hvZGxlcl9ncm93dGhfcmF0ZV9ldGgqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzY2NTAwODg1fX19XX0_&Signature=e0WAU4fz3L273I8IZjHlzE84-aIVAOqU4E8JRn8uGpoiIoRrP8COUuz55MsKwbIgZ0UlbxVDBJFIkiJIx~MTD6L4RkddM3sp8NmA6Nr2jVe8hxdM~XKsFcHevHVA1jGG6RmCegwQ5yrppvf2O~9AKL4cNZ3e4ocleKgR5N74xtbICU4d7YNqKWVQpeTrRSRh-tZIs1coytE-UCHshu~6owtgRYUcMVZNh8e8Tcnn-lMiI5Xc-F8qzmuAwX-pRIF1WzX~50rLHuvwO80IKeI3QCrHLHtG5B9eEtAy~b~3z1cOqOjoDnO7k9YwbJ49qvp3OR2nIgyRk5P6OiB4Z~UBEQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, 
    "cdd_trend_eth": "https://api.caprioletech.com/v1/data/top_models_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3RvcF9tb2RlbHNfZXRoKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=XkXCmqVsNAOKsas7AQ2k7hpkAikCZxZlXO0N32gpAu4OQQRX7sOLXYY0QO5CzYwARTHb7VbX0qMejMQHQIyyqgOzdJlbXC32CP1M9TI179IFk0~k1P2rZyqAyiTzZx~EuAXxDdrOD9w4CJGBO8qnUHlUUHiI0uOfo5cbBOnvFIa6RWdZPHRLH4A43jB3mtctyXEAXucBe8ELjnuAS8xuhoQtg45LHg6TooI1IV2d1EVFICaV12MMDNULdVFz7Zpk5GCQ6wSWHd~2pIgICNi0t8sL7N8oEJsHEqpSWDW4HAqH5GTQp45UgFdTdoRM3oGsS0LCEk9bP2NNypsZXRKwHQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      

    # ALTS
    "alts_speculation_index": "https://api.caprioletech.com/v1/data/speculation_index?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NwZWN1bGF0aW9uX2luZGV4KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=O2WExcUK4jg-kURXWuhpRoDKgoRH1zs2ZSPLvzfphGZEzMzWepPsGFJ~lOH1waC6hhoNFCTskTISHhv84Dq7qaONrGb7KrRTlsE5Ir2rjfLAtbvDmEhzyGJVmpFKTqcbJXToOMfGtdMR2FZHCYV~-l~kR67cYzXEiaazGZa5PIrMHoMSoQBVLxZh1EofXHiY~hVhKBEPFe0llK3BknStDy0lxGjdQGuHn6ce084x8216xqpc~aJjm8UhtPwJzcMIVzeTB7fcyze9egIhsZMOAL-6PiCaMFTVl8Kup1C5sCEkA6H6zYuwh4IJV-XfkZTihN7V~3l46ddwGAlNK6ijUA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "alts_crypto_breadth": "https://api.caprioletech.com/v1/data/crypto_breadth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2NyeXB0b19icmVhZHRoKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc2NjUwMDg4NX19fV19&Signature=vTJkpYhPlZYK-EbP2rx7xZfnD~orZjb5QTKMtx7TfGYwuRzg4y-omQF65TqgBiDFMHK9GlxfaCrWynYCZOzS5T6m8ddvvGwriKAwvjy2r~p9er-wLK0s05ZXQozrmdfHgvN7CR8TGITC6CfoVr5cIuXoseOMBn1vp1Q4U8G5gKKzhuf-oZ00kfxIl-iQ1YjK9c7i8EB2rKHUq5r5vlajgfxVU-7GVqUkScGZmE2lppdjK9GVXZ19X0TkFIBdWSu5tW1ILAhtWWsJzyDySEWBIEESfFV9jsnObxBcqC2OoIczbz1DpFUBk~DG88nrRnMFjcgp4QogKFm96Kz7HKY6Ew__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,

}


'''TIME_EXTENSION = "&begin=1601856000000&end=1759622400000&countBack=1827"
SIGNED_URLS: Dict[str, str] = {
    # Use webpage Network Inspection - copy Headers-Request URL:
    "macro_index": "https://api.caprioletech.com/v1/data/macro_index_btc_osc?end=1757721600000&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21hY3JvX2luZGV4X2J0Y19vc2M~ZW5kPTE3NTc3MjE2MDAwMDAqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MTAzfX19XX0_&Signature=D-9Rh-v36WJnBH7SmtcmzreJ7tqQpDT1d6BJKQPRtKxwrVnQYdWOMFgg9YqEzPt2xPL1X1YdPanh~x-4sWjlbtzKdeXlJS65Pq44L2MTAQlATt~0udKU5cFHuMmBoALp7VeQZi-qoan4ROH1537yST-nOd-~dlIcwc3oHAn8wSKqVhoRv3r4qHvnEjMGjshX6byMPKeWhqlGmLdmZCKZhmd0y0dQBDhG5MZJjlWDb8tHfC5ajBVhgAJfSO7DSdMNSO3j-iWguE44WwlwB-ovw6YaQD6mM98uYAtobgMGvTE3scyXD3IsrOcHen3hUWF5FlSpPriYVlaZpYLtXD7JPw__&Key-Pair-Id=K3TU5BJCZ0S7H3",
    "demand": "https://api.caprioletech.com/v1/data/apparent_demand_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2FwcGFyZW50X2RlbWFuZF9idGMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MTAzfX19XX0_&Signature=Z0j92Zu3a4lhyzmmMG~vfvu1OjtOG1mIVvfMkYZkbObYeu1TEuYCJcpinJYK83tPsyOVqDOSWG7kMnfWn1DxFWJq7jVarPuVTDZtYih1nDCODojNZwBILtNYtzCDT-sSJaMM5MOGeYoM73t4S1Nuj-XvIV2jOQLJTmhQaL6KPJA~rIlpp4sdJHWMI8OUDHSFtKJHr-XRWQSW6sSIfhHRU-Hbwfc8akZCMsLwNxC6sphIZjDP2cnQc--ruAYf4i~g9hhVriu3xI4AB5DdgCp-fNX4OKWDXtotbLoR1zxgIJF2-L-nx4dX~iUW1gvZlIGaN4WwNtd9sIr7qJWYr647Ig__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,        
    "nvts": "https://api.caprioletech.com/v1/data/dynamic_range_nvt?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2R5bmFtaWNfcmFuZ2VfbnZ0KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDEwM319fV19&Signature=MTSS8IgIGHDA76JXUBHqE06Bmd8K5fhrQHl4CP0jHNwCZapWyhzJGmU01~iT4oEx4-Bt0waNEiCbLxE9tezqbf8H-6-M9gQ3qBThpNlwWhAToPwg5J8M9qi7YDqHIx2dO4gXEp8MQj9Xt9Ux0GrvQ8jJmm5IvuOTntSii1mXgYxmADb8wuEup0MZfDh9muYJiDS9m~oj2ub21FRu5grTlbg6Vy0jvsWms3NmAGmucM2VZWmUi5BaG0q9Duj3o1Ai~lqyYJgdZOFRVHapnlEsrUY~9D3xmeRZWCNWgKh8Xl76orM-WQX1swphn09N3axbBwcEbMxkKQQZLciM5tclIw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, # Dynamic NVT
    "energy_value": "https://api.caprioletech.com/v1/data/bitcoin_energy_value?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5fZW5lcmd5X3ZhbHVlKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=RvCGJE6Ne379OBiDgGHGSpVvhMT-PH1yesaA6da-DNHwUy5-TvKYhWWLifb7oduv2UPMmDbJ5tDNzZi452LrXZTKP3ywQuIStDbXGtIj7HHQBQJNgNy~PoOC1GsQdo~4q8yhAp-dGDHeKvYG~uSkImH-psqHqi293SVyiWUTMAkRbUXc8t75goBQdhV9R1m7BWat36wfGoaPefXDeZbHIRkMOV8I6VITXzP--4iIlqyHhloznwr-XMVm-eRbESO6pEZgkq8F-wBLhajJ7J1ItAjWw0JEs3KDagamttGVRmTATU4Y1NYYBFvrdHjGWSl~meMfgfIja8b75nlsDzaZEQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    "heater": "https://api.caprioletech.com/v1/data/heater_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hlYXRlcl9idGMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=DbSzkybGjTarzcJcV9GTAl8OCfF0QeW-ph7tiLV6dxqv4M2-A00rBro9QDEXu~NtMcOzMtWZ~pJhYZziIJlA~QMo~ijZqVCl4vfqgxn5NfxU2L-rwwo97G0VD3B2VCjgjjwVykzPt3z~2LBf9X5zOkGxC0lwFdVVHCzNwJSk7rd66ZUEs-YBb95t4wq38duXQ9wwiVEgEBQjqrzuMgUS4EHjd7-53IvY3-iCqf6iymN3Q1B~iOWnrjBExWGBzdnDFVNQIerBrJch~AciEMRvlqNCm8qxYQvoASwGcLJbMx5801oONNbdSlTpk6fVM9fahNJfdGZWzfyHzCFwdrP5Bw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,    
    "hodler_growth_rate": "https://api.caprioletech.com/v1/data/hodler_growth_rate_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hvZGxlcl9ncm93dGhfcmF0ZV9idGMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=ZqXx0xcXq9~tgJm17VAXDODi6pvy6nw0Jny9FQePcWOnVNShG7vP-cgQZ3~WYE-670nwTrWP6CV1MZU1BnLYndXOMHKaMw2bvG1TtJmKkjwk7kjA1Eme-rjbvoNbtoLuUguOhgf3hZcx6OiyCmMFWFzVw9pNAS5YK0SCRzvDWj9LpXDtxvQdlq9B5UUokwAEDsTVkCDfGfNRbsM88TuBxu6TOk9gUymocZuDsMIR3nGDVmhAAzgxI1KM2glwbTQbDPxj0Vf9ponYL8z0492QNN1AuRCSiyYQ6xezVQQvpjchO-fx9g2p-tPvw2ZxK2HddVZanD5Co-U5i496CKce~Q__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,     
    "production_cost": "https://api.caprioletech.com/v1/data/bitcoin_production_cost?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5fcHJvZHVjdGlvbl9jb3N0KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=L8lFBwJoPW6BqGJpozLacRTBdQZEkVwTVQPvCmIpx7APJRGxhcG0rvBIbl19JWmUL9dLKZSbLCFYkR-tpZMeVy1wVs4ydN9-DLcOCvinW6fZEvbsS8PJSKhumAOPmSKZG1RkpO-tmYS9sXK5584bPVY6MsR-WdlmVOcJqOFGIx3CksG3F7H1dDPB2WVUum3MuPR1hvqHvkm2xr65qZtbjPx-DJntbN38wGqGMRswLVaCfQBCqaCZz4HmmaSoiBcXQRgH-7Cql5dUUy0EijtgRwmtyA9XqEd4rPSFc4hM5f2i2CgVHNI-f-s2CyJ-Knn6UmnU1fEKtenShHWwCSBd1g__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    # top models: supply_delta, cdd_trend
    "top_models": "https://api.caprioletech.com/v1/data/top_models_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3RvcF9tb2RlbHNfYnRjKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=PTehDYZ1fdaBfaUtGuLQOs2NHIVyHwe7BgPfPdKHEX93~HegxETOX7MvCpWq1CM0RFpeE9Z-B4g31mR2Vn7~u68y~gJurpDto-a4QiJcnxAVsLD3Y3G7NsX5~4IcKWeQ8oNTlXCq7WYRRcxo8CU-B7AluP6JYuSzSxstzGi~M9eCSep06hwkrywZ7eDX-2-LJKvsedJYIJkldo~bT3PFqEThR6gVeLs7J2YEle~5bFql95IluAW~v2uGv5xJOGGwBk3xziAPj2ViUHMSBEqYJR51cfOWLMi~JgGTHoJmahVSPPJLJiosu4R9~XIGURGV7nyKrpmvdH-omgWYYWOL8A__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,        
    "yardstick": "https://api.caprioletech.com/v1/data/bitcoin_yardstick?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5feWFyZHN0aWNrKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=cFmkY5p9sMVM874GlL~BDiN~G3asDKJXUIpEioe1tid7MHIr4--vv5Gr8Iqiq0OLHhBO4oLTemqU0wIfa8NqV1Kb1BENpO-jSoPG0PgvwUgZZBg1RenPzptZcvPBct18lfRDdVN3LnFmTQbXj75yGxdAIzvvgLq5-5TW-yAHvKvfH6swQcW0hSZVFiyoYiwxqyyFoPIDX4d0~lLgYaHCNxItIi9vIExpIWHQMgBN9x5sjzq~0Hy0W1VOBOz6Sva9U1ZeZQrLzD7xAc7FLWIxAVulUy9C1dBf6Pj-QuQj-yzlmEFAJqUVORn1bgn3xbI-FbK~1BFXjHVdyMMt0xbthQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    
    # Treasuries (Institutional buying)
    "treasuries": "https://api.caprioletech.com/v1/data/bitcoin_treasuries_aggregate?sub=Pro&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2JpdGNvaW5fdHJlYXN1cmllc19hZ2dyZWdhdGU~c3ViPVBybyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTk1ODQyNDh9fX1dfQ__&Signature=Ng7c5lUchLjXTAAh23A7Xz0rvyN4fRqi6dovrQSnTD8fnECKWOamEx6ypaIAv7jdOIR2PyaSaRmQXi-6ToadC0wj5GFfhbdfx6gRha-mHC3iMPjTWJ~Rxlvfzc45pZ5grmiAztbOmR2UkD9fO0m0Yplfot4xVz7nRfL2qXUKubB-4Q32ZpzlazG68Xp5E1nvBCRI443OEucRofpmiIJpFVDoC8zpoxSB0Tqpy08dbU~eZeIWRVbwOF62AFNnDzN1Ju6aAWbIzJm14M~AhuYYJ4wf0mTGsKx~svs07pfTm~wDkaVm5EB6Cyd~J8wsYcXgv1Iag-kxsBq3nJq2qttCAw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,   
          
    # Sentiment
    # spread = bullish sentiment - bearish sentiment
    "investor_sentiment": "https://api.caprioletech.com/v1/data/sentiment_aaii?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9hYWlpKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=D8ua6o4tJ~v4t6~-skpW94EBY-Ejw5reU2NFD5A1rrvT092fREoYlgWzTgoiKM1TeHL6dnPVjDkSbc0AH7e5FaK2nSmWjih-fYoix08qLIf-N8zaV5M4E~FkwtPUTy5aKzy-pZ5m6OVTgcm~gtq1YiJjkXHQNV15~tE~ymeioc--DFRTAxaJVT4Zx6jQQYo56G0CzsZxHLoP3u7V4CNuwNtZVIAfqMQlIJVV~gr7tweRGsOMk6n6ETY4I2RrmNSyEQ-VqB00RQdaRS1YYPBtQPhR-d399Sgk1h9dWwN3X3mfxvK3UxxudZM1JbC6Y7KjIYKxKEECWT-b-TKA~8IvTw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    "active_manager_sentiment": "https://api.caprioletech.com/v1/data/sentiment_ams?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9hbXMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=B30aB4q1UYlhmwTrXo6P7kSZ2FMVLLozG3t7OMbGjezYN8z6X-iso4SkNlClhX-OL6RcT1D5vTgyktKjlqoETVLtn5sqQW7vH~2lFBal7TEchuuUIeDEQsUSM~RXf4B0gc4ab2s-WQVnwN4HfsCGN2pSpm3wj8FcThOijIq8EUrkW5hz81~2pXN1LHIaGhlvTyKN4zfYfJXbNnLWszZLPDANhnUXDg-siQuTrfPLHLHN3va3vHb2caNDm4KFxqkv7qBDx~u0qEN~z68e~ruqc8YvKGGrKdaA3vNgxgIensBT~lEn0-DZpVeFIwztuAKUluqGp1lGbeEPubHSfNdrvQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "business_outlook": "https://api.caprioletech.com/v1/data/sentiment_pf?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9wZioiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTk1ODQyNDh9fX1dfQ__&Signature=SMgbUvyEmr4Dw3g97Oa57BaL8BVsty7Im2VYUtBSjL4f-05DCREFS7spMBhs6sau8Y88sfrIsMdIqvG8f6JBdM~mngPB7Qvf2mENMHtM4YHC4DZD8nBuedB2SoDXI6b5EcIBSvHo69WO2LGfXwwe1-mMCf3lhEUxHelF12FLNlabl3aI8sIr604mOCSM1WnWsdKCKtKvpfTcjFs3cB7dzAxML9nTsoe4cXq4mwGIIY15GNF-sizLX~frqrQS5OiU51bEUrbeYQ5cLnvRqD~8HiOgxq81iTCQ3pq3PtCqREDQ3rznQcI~QV5cbHd1EOwAq3r3fsLzA7~a22ojEezmGQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "equity_fear_greed": "https://api.caprioletech.com/v1/data/sentiment_cnn?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NlbnRpbWVudF9jbm4qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=NDd4danRhF~Z5xhvaRo2HOkU4QlFiPjV~jPcIOzguC8Skb~PwKTnktTHAy~h7A8zFuTvP1NEMgqydtLM0R7timIqCXgf-WwtWVPQVSNGvh~tjEzMHEdC8rjfvfP8LayKmAJhzFWkSRhLLd0XX2Z35UtG484qkpNA9djLROg2p5lLAKC1LMOWKKT2I4SOMzK7l8U6XAZIBPyp4Vo2qj2KZmq6G9Zif4-6YW1jqa7gb5ihXgI3QVzAXQcKH44g1LqnRHER0Cv5wHxOE66tleYDTjPRmOKqGm2elSY~z~EPFdxf6sVmGRnoHJsjQYf9yfxcg1R0pr8HD1yLzdkUUdzDDA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, 

    # Macro
    "equity_premium": "https://api.caprioletech.com/v1/data/equity_premium?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2VxdWl0eV9wcmVtaXVtKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=M62Kr9QwJx81afg0iSLC8OZrJe6ZKpmlqlmfUF6AsmoiIS2mmRvPDtHs3W1yP7UGmzyA2uGQf8G1FWMa3U4tBxf0TzgXswhnBl~LryVvWf74efkdEDdP8JQgJcIpjuRQLOv~ZQiR~NmUJOKg4u7NDUkfoFns0cXTb3FIB06pO9yWMpP2YTy-CjRM1m93mHKzGpwvR8z5OJGvHGE3OK5Yvju3fV13ZcGdRbkY08ZcjZv5mEAJ4h0CKh4A~FAsO3P~h~MG1QayI4wwf422ntf6XFS48-DOV9PMiw1SI7DJOfEcvvOEuNVzTcmOaU2rHmyc0W9RAyLWSOPH85Hh3nbFtg__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,
    "net_liquidity": "https://api.caprioletech.com/v1/data/global_m2?sub=Pro&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2dsb2JhbF9tMj9zdWI9UHJvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=smhwC1p45i2rFlYUrZqRn0TQp8MTuF~T1zF4kTGC~L2BYAu10yVMHSW2CR7Wusy2OjvCYfM3BL2GgvzGMvBTl0qNx4KKnD4JmFExb9wUAf~TmU3TSKx9VchUiEO859yOy~KkViL6JUXV881AZsMGMk2uO5Su7U5n5avDtqvYsgeyNnn0CGsBAYjk-h-jcIBpzCJAJ4QSIOPgC7eibjjpG-2xVlPedHYbpAfLEvgsF7xx97JVBidRLqD4UF9-qJwJSIERtjscjtloMx6DiAD8PyKin-fuT6LDdpuZmJSMJJKcpNYABIpL69pm8TtBu~m5jg0TFXVhNaq7c5aMV5HwXw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,
    "gold_stocks_ratio": "https://api.caprioletech.com/v1/data/gold_stocks_ratio?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2dvbGRfc3RvY2tzX3JhdGlvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=q6FJRR9b6zWGuC9DJbkJJjeEy~YG~MgjC-iSO32vk6WF6Us-TCJyLCi4qu7-Ortr4~Tnlivs38Ux0LpzZvX1GMiwKafvF10m2-RwOlno1sAh5ii50Y9EO5uKpjCxj0vBwqK0Fvy550YIFDiSNCproPoPIsue64hneTndmk7jKb2DOn9yudNDcb15Ocqw7E7IWd7ZeH51XlIhjPGDEYfpB8na-Bf4LircRA5ovYBrVfjZBZgVcLLUaMc5tkN8luKdsKxFX0f~pmqCPFiCopee6j9keC4yQhNmJygml6lhVeKfWn7n8er0Qept0jU-BOLW5rqRQ~OJkMv2cxxXv0MokQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, 
    "insider_trades": "https://api.caprioletech.com/v1/data/insiders?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2luc2lkZXJzKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=cgTdsy6Amb7BewZ5JN0si22ewaoKTGqgd3nLBWhvs6fmPngHW11z~EHLksFHCq8E67OYxn-YB0d6w-~~8TRyBtiJtNn6h6eFhMPGBigw~TO8-7mS3uW7s5ZoyJcBqkVE9mAjGanrN3USCEGgRu5MeoxUtAdUuEJcoHcL1NXsRKjSjAzie9k3Vm4xOGGThak1-EEHgrIktg2VSv4j4fRGeOMdSbOH2dngCF7OXGyH76cA1dp0WXrzEn8Mgijym7e1z~WTjkHxaDgtj3Zzsa2KeT8vE7KbCfiDkDSQBYvxialPicDZrNWZT2cV2HSo5LdOuuAot62bBwG210qbDcRMSQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "market_breadth": "https://api.caprioletech.com/v1/data/market_breadth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21hcmtldF9icmVhZHRoKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=rneRHMb0OfPmNoR~Qu94VVdT2r4ckVKf6Ra86xeglt4tx3JdBF6x~WbXeV7i0bhCvKiN9Ox7iLEE0ESz~ggCVngwYboGgQcsH~-B7ArrKq9tOGEwnXYLNQWt8lTtfffnkmXaL19dTHZxy9OLTixqh-QaBfXPhpo~jE6GnVIG-PLDHsZ-08fQjTNRcW4EoLUCnU5A3c6YWIZHY~hRIrNXqrTEnXun29RIZcEDj-cvFtGYsXt5l3RKARVq~ZaDPYHOm~Dae8CfjT4QoZ7E9RhlB5aKdjqpe-V8Fdsoeo~JCRRRrPfuwxTphLFK3cuGXo0ISV24bDgbIdWt0~rkxIoaKQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "sp_put_call": "https://api.caprioletech.com/v1/data/put_call?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3B1dF9jYWxsKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=bnhGdSSPnLVD8kT5STgf92DwxvO~xtelnh00Wag7hzy-QeyXTUZRcao7UAvrlY129x7ZyWvg7VR2CmpiN4Gd6as3fZLzvq4DrFcur2XWgFS4xu9G94lW5j3L5jQf4wG~So5QMR3ofN9NhdZhQ6TYlNfT5bggDgytgyB0ZmULLg6~bvgTO2oIaW5zaC5fOH6oGf4C2uj5SCgnBh2ddoGh8kpx22RJwXRfuzPMyW-QCFszePzC9RqkyUIOI9DclGXhrAWIk7ay4LloiZQX95iud7rCUiPn5CousLEH9YWnc0qGQRQhRf3pn8ruxb29rN62q7j-4MsgTF-bCSStpebiLQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "us_liquidity": "https://api.caprioletech.com/v1/data/us_liquidity?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3VzX2xpcXVpZGl0eSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTk1ODQyNDh9fX1dfQ__&Signature=BFqOVAhqlPZ56Bn6BJXjQgY3sYboJm-dsZ5xAumBIbGeCUAJk5-BE1dS9Ndze0vwi6icRQUCt7u8LP3iWLRKZpXvLKYIIEARUoCajg~3U4CqOlFHBeLvlVJZaLA8R60a8Rk-qGPv19NZIgyGLy6Rq~oLQKLKqMvhIu0J3H6cYRym581X02WjXewIYh29MidDmQddsUC2CTBxtceSD4Yb1syEvw9~CV5NE8maGoCAtbuChY6vTU9-5B9B6kuTpvT-TNosDkITMm36ftN7UVOxsNYv4CtYeQ4xqSS1cxuyCw-yNxmM-~yYj6LH-nJwP1jy2zvapxQgukO2qJ0MM3KGQg__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "usd_positioning": "https://api.caprioletech.com/v1/data/usd_positioning?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3VzZF9wb3NpdGlvbmluZyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTk1ODQyNDh9fX1dfQ__&Signature=J~9sO2N~X5Y8rw7YsQ5GTqyVQ4MjLSAKPR0WM3burXliwwwlqTON6CtXnlGwxFFAAwD2fdRnQf57U1hAUO1yvnmrvrhpG4BNxnFqtbrZabDc-HJ8C~cc4IF8f3oStIWkUfekL~fAsATCJo8-SGRJh0iuTVpi-gc8UOZOaWNKi-ZNwnorHDQEG0mH6QWsJwHv9gx1TrfPFWgyIg07qBy0G1PoewUC7CULNGvv~2-4jCMHsxKmIXLl1TVUbrAGWxB1oxSfwrasfqp3mP0XGaTNfOlbljv8CD04VZ3xMh0jzwVxiTE4Ypmn8clXGsaSo2RXQ4ZTOzGypHcchefu0226sg__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "macro_ratios": "https://api.caprioletech.com/v1/data/ratio?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3JhdGlvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=TO7Vuvnns~xPvAVkekpyPYkAMkJYCdz-6vIgVlqX9aGUsbHOXY8Yj1eEnnmBQvtNCTOL~0-ncQ-1Hb4guqEVLdU27X2KAMotjNSOjhFTIv~TzgqBTuaSvGNRfDdWRJ7dARHP4r5FFW445bSDDv4wQbNvV0MIhlTqHbe~gmssd7aw8v62tAKLJ0KeUE0R7VGs0B7aDy7xKthSj1sLOVUlyc0iNP-wBC6mPMfPTJqmv2VBsYNzYZAKtmU1gPgwGV9A33Y3R3YOby7cqgrW6hDjL3hlxsHXCprpddznyPa9bVq73jGXKfajfG1FuZnEsLsjhdJKzotv2M8rXoUEE75qZA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      
    
    # Strategies
    "midas_gold": "https://api.caprioletech.com/v1/data/midas_gold?end=1757721600000&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21pZGFzX2dvbGQ~ZW5kPTE3NTc3MjE2MDAwMDAqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=IvNi2U7dtzVJKHQQXpxD-WTOTQ3VGwmeT2YFqt~WkSdV3CkQ95q-iveGpGGeBcedlVAfk3UXOQs9B46wFM4ERpY0Y6aRjQwkbWfyu1DbuwQuBL5ED77jruXizfoDS9COkHdE63grq~SsBuECZOGXxOgFacQQoS8aJqX9AxjstuWxwvy4pnGlJrQ6ydeuYrrCklL7RIZRUQV2~LOyiUfnUQdgiHGaPRDxqZxUIJzH6fL1s-myMMOCfTRroIvJ3YUlJHV0JTBvJ8EkhBRLHrJY33l4CXu95LKlieZ4Vl~spfAHSM0TE0leKTeUgMPgZncrkW6Ped5XPhKRtPe5kwOUww__&Key-Pair-Id=K3TU5BJCZ0S7H3",
    "spectrum": "https://api.caprioletech.com/v1/data/spectrum_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NwZWN0cnVtX2J0YyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NTk1ODQyNDh9fX1dfQ__&Signature=hRLTptMmiP453WLxCrkFzdTtNuNOWw~T8T8zqiPpVxwRsLlTkLcsgrRQjMD0l0vpitCQfukRbT2uAmhWoDrIoqWtcCN5vGQX4pUC6kWMeCcJ0FW9vrWHZJ9Rg-zeyEqA6mmTbd97kW4xM6ZMg8LuoMKayABTFEHEp3ldVVcH51pN3WdrdmxbNvVVxbQh6udvZ~cok2P2TrsNI9xIhvw4S70afSTT09ii0O5ajoSFfR2Jw8lvjbsIyb7Vwfdp~a9D4znDFkEUjNud4uITV3iyQITd0QyX-bk92aaiVZLYo52J8VlFlv1zTdDQYfjEnYdUeI0caDgjlUoHAQPjsTU7bA__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,
    "node_strategy": "https://api.caprioletech.com/v1/data/node_btc?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL25vZGVfYnRjKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=tVu-jDlZt6wioU3C~xJHSR2q6e0kKd99PbfP9Zeaf67wn4Jvw8guUXLuqRbTHung2vlzpxKQEyrw8uNgXxth9VEKlJmfhMbx3Jf5lqkRd72pIhFSaib6xXUM9TzFNxJY~ts4HMGp5gdXqYbMVAjK3ccsnyyLyaebY9yeYcdbJuYQXXBTXRDYGDsYImkwdJDtX6k0~54tVGndA7A6geEq4wDQAChwqT5A-2bkZL-QAO4mRtMCbQWgSAbanZV85pR~PzUxp8LeIf0lIWn9wlDycVAQmx~OpO8n-lUR-sqm5AsXD-8YDlugnq-UoIFmEfJfOPPBxWckQxAXOHAW0CdMYg__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,    

    
    # ETH
    "macro_index_eth": "https://api.caprioletech.com/v1/data/macro_index_eth_osc?end=1757721600000&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL21hY3JvX2luZGV4X2V0aF9vc2M~ZW5kPTE3NTc3MjE2MDAwMDAqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=AOKF2b5856ZBJRzHqS1YfOSm9TQStRTDQVD4TyKE7txLW60BRiR2N7oikM0Kp-50Iikbi0PQQcdGhp2BI2j7hJsFDSFcMenO2INLZOS97i8FqBmz-wGxwekwIgOjKd09mfoL5sI7t5MTGgsuWtsMROh8t~jn54~dxLH323xpL9ZB5U1UOj1t5cP7ysySbj4sEUnhaowh5HKzz9FyG-DX1ItpD2ilu2U5aEJQjtjEB89AaZhAoQvrOR-gpFMHgpQbGEbcdtsfLh-wLjqaWT29bBcNA6I-7zrPzkApNzKUjLNoXrwV3QgbNSbR2VO3KAOfTnXURq~xaq8I~rUm7LAUqg__&Key-Pair-Id=K3TU5BJCZ0S7H3",
    "demand_eth": "https://api.caprioletech.com/v1/data/apparent_demand_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2FwcGFyZW50X2RlbWFuZF9ldGgqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=MREVhwM5F~ZFyEyjg0hiUS~U3DLGzyOFrRIegXuhUa75koggAK2K9aZIOnLdcEjhogBwtAmuOIv-t83GLz4p8GTsY4M1wXujG4H0qR2AyfYHAe6E0suDkoXLIe5xYV0uni8SSKWW44o~QZYCuVeB1KQgxDsboSZFvro5WW7zYFeXMJiLYMbnDLySITabh5dPDtXVuVC1szKxwJvzmp30Ses3SvwLvJUnzmCTjgUAc~DJRelElb5Oiwp6hXIhwZsm8pWbP1JedV7vrHcK~OtLe-PPAH4nQaBjqZbekHopHMb-7oQKHY8yEN2rmVyMrGAILBAyhCStlj8iBRNZrZSYnw__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "heater_eth": "https://api.caprioletech.com/v1/data/heater_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hlYXRlcl9ldGgqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=soMl3duzC09T4OZ1GdxjgkKt4Uux1BgVp2Bkk6C2BBbJrGFcjmTu6fN2H4xfExZpB69Rblx9peuAgrA0XUyLgtz1lC7avchMttWxOlQPOn-CxkZ3ec2zuhu7pJnPylcE9Poji9m0zodAjFPe2yPqoLzB5MrkVPYDnyYP38-Y-WB-MwxkLTy7kEbVZgzeJLgZm4RlHUEbIEH9DRlyUdPQGjfzPXR1eyWNBPGFJChAeG-W5sO0cwClGzIHAdDkfYRwAvdcov~0CQ1QiggRiDBsbl-BziC2YD-hbEUG~SFMqeUtxeTMDmPbgY4bxcd2-X~0G67S3F9JyiorIOsgWBevsQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "hodler_growth_rate_eth": "https://api.caprioletech.com/v1/data/hodler_growth_rate_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2hvZGxlcl9ncm93dGhfcmF0ZV9ldGgqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU5NTg0MjQ4fX19XX0_&Signature=FvPAh~MmQaWaPlJmAbfMc5T~8sth8TFLRr~RxeysmPwIOT9lFfOl4ofDGoWnD~oVbJ0cSnWop3D~9r-M1~0ZXTobYmVkjZfq1~uzwtbBGRYtrg1xUr5vKIvAzrKCcGA5pOChG3a2190XzyI1nzD~mTfYSNad2ya-zt306L2QOn~raBPXEODIBC6pi5-lcFUJtUcywgZEaNWsAWAwjdMoq-yr2U2bJb6Z3nCkmsDrOgjecSb4BFo5E3XVKNhM-n3rkqX8QJ9Hd8nIwYfScnCixB8wnNkbcVoXMMElCrK~hg-a3ohFMWqolMtYSjPiqPLrelbGFfjAU3Txv-IrHDFNSQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION, 
    "cdd_trend_eth": "https://api.caprioletech.com/v1/data/top_models_eth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3RvcF9tb2RlbHNfZXRoKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=A2h7Kpy6Z6zRWvz8f9mKfBJaCk35jIa6b6H0NzkMXBWnZwyIDNg0MzDg15yR~YskBQ-MUJ02sUDL32B3uj6A~fviqGEjK0hKje9NnHNmxd5C9fyq8D3KRvJdrpUB4w24YOpw5DOS1pj68YNfaJt2bgAEq3VYwNwWcFHVLvA53zyf2upSJbthU5PbZzyAKxqQMff8PjIWGEP3Bo~8C1-NbN41DVoNueQf7TlG3bh3tD2hLU09tc7otv7f3AICngyg4snJ-P0uyI7~LxTHHLXTeg7JnXcKA1M7Mm0o9W0k7vWbpb2mfIGTw9TyW0GeGdU7rotz6CqnZMkiRqgxBV8d1Q__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,      

    # ALTS
    "alts_speculation_index": "https://api.caprioletech.com/v1/data/speculation_index?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL3NwZWN1bGF0aW9uX2luZGV4KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=jF0UHlJPIpcn8ArlvYwco1uTamrka8zMokbXI04e7J8JGeF9oFvKDVKcZOWVOEASwWzf3AOOz5Or6x~M9~cjAMcWFIS3V2z~-beRVZq3LP9uLEhq7KUaVGW1fNaXfSSnpmqCaPJt0WJIYB91IxYcBYH6ohNZAi0acNebH8zkTQlajZZIElSQvVC-QmpGilLskhEQdKX2dDxOE8zqlg3jEv6miwZ6wW8wmiKrSjp2g4yJt9aQwPgLG4knASIJ53f2KFpyQj5km36v6qMOeqXDs12-mxti-B7-2u3VTGpOdPRbxkI4W2SR6cWBtqxdJCD4rtb-GxuQzPvL2CllEfZgWQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,  
    "alts_crypto_breadth": "https://api.caprioletech.com/v1/data/crypto_breadth?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9hcGkuY2FwcmlvbGV0ZWNoLmNvbS92MS9kYXRhL2NyeXB0b19icmVhZHRoKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc1OTU4NDI0OH19fV19&Signature=mOCbVDbl4m4Ian5Isgg78MRNAapK~VtzfvGUS1VW625cnawE4gb78Vul-dYoxaoRGZXe0UfOrDrW95eBooE2uZMi~CzuJiQVIj2TDbuMZoDkdRYJvTPolFGVjQoFkUtjnpaH6Yi5CaJuUl6swRDfxKjpikwlfz4jEOZfoMZzxDeo3BIocPKgNDjMaTd3iixziLWaTmxNpzUBUF~svDaBzwhVlQgrx0zlIblcs0fMunVRpl6Zb8ClLQndi~gzWxphlryKhA4RzaWe~gYbJHeC-vnRs4WvCLiRNG6E5v0N~Vu5NHkXNu~B8DJHEVyEjnSyn1M-5lIHDNPD8jmGAYUhPQ__&Key-Pair-Id=K3TU5BJCZ0S7H3" + TIME_EXTENSION,

}'''





# ----------------------------- capriole_main -------------------------------------------------------------


@anvil.server.background_task
@anvil.server.callable
def auto_import_capriole_data():

  def _force_col_to_number(df: pd.DataFrame) -> pd.DataFrame:
      """Force a column to numeric dtype, coercing errors to NaN."""
      time_date_list = ["date", "time", "timestamp", "Date", "Time", "Timestamp", "date_str", "time_str"]
      num_cols = [c for c in df.columns if c not in time_date_list]
      df[num_cols] = df[num_cols].apply(pd.to_numeric, errors="coerce")
      return df


  # Load Macro Index
  df_data = query_capriole_metric("macro_index") # Macro Index
  df_data = _force_col_to_number(df_data)
  df_data['macro_index'] = df_data[['contraction', 'expansion', 'expansion_atr','recovery', 'slowdown']].max(axis=1)
  #df_data['date_str'] = df_data['date'].str.slice(0, 10)
  #df_data['date'] = pd.to_datetime(df_data['date_str'])    
  df_capriole = df_data[['time','macro_index']]
  #print('DF macro_index: ', df_capriole.tail(), df_capriole.info())

  # Load Heater
  df_data = query_capriole_metric("heater")
  df_data = _force_col_to_number(df_data)
  print('DF Data: ', df_data.tail(), df_data.info())   
  df_capriole = pd.merge(df_capriole, df_data[['time','price_usd_close','heater','oi_pct_mcap']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load NVTS
  df_data = query_capriole_metric("nvts")
  df_data = _force_col_to_number(df_data)
  print('DF Data: ', df_data.tail(), df_data.info())   
  df_capriole = pd.merge(df_capriole, df_data[['time','nvts']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 

  # Load Production Cost
  df_data = query_capriole_metric("production_cost")
  df_data = _force_col_to_number(df_data)
  print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"Production Cost": "production_cost", "Margin":"miner_margin"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','production_cost','miner_margin']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Top Models: CDD Trend
  df_data = query_capriole_metric("top_models")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"CDD_trend": "cdd_trend"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','supply_delta','cdd_trend']],on='time', how="outer")   
  #print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Apparent Demand
  df_data = query_capriole_metric("demand")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"CDD_trend": "cdd_trend"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','apparent_demand']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Energy Value
  df_data = query_capriole_metric("energy_value")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"CDD_trend": "cdd_trend"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','energy_value']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Hodler Growth Rate
  df_data = query_capriole_metric("hodler_growth_rate")
  df_data = _force_col_to_number(df_data)
  print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"CDD_trend": "cdd_trend"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','active_more_2y_percent','active_more_1y_percent','active_more_6m_percent','lth_supply_percent']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Yardstick
  df_data = query_capriole_metric("yardstick")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"CDD_trend": "cdd_trend"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','yardstick']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Treasuries
  """df_data = query_capriole_metric("treasuries")
  df_data = _force_col_to_number(df_data)
  print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"total_institutional_buying_excess": "institutional_buying_excess", "mnav_enterprize_mean": "mnav_enterprise_mean", "ave_debt_to_enterprize_value": "ave_debt_to_enterprise_value", "days_cover_enterprize_mean": "days_cover_enterprise_mean"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','institutional_buying_excess','mnav_enterprise_mean', 'treasury_cvd_Z', 'buy_sell_ratio_roc','companies_buying_per_day',
                                               'ave_debt_to_equity','ave_debt_to_enterprise_value','ave_debt_to_bitcoin_treasury','yield_mean','days_cover_enterprise_mean']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) """

  # Load Investor Sentiment
  df_data = query_capriole_metric("investor_sentiment")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"Spread": "sentiment_spread"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','sentiment_spread']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 

  # Load Active Manager Sentiment
  df_data = query_capriole_metric("active_manager_sentiment")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"AMS": "active_manager_sentiment"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','active_manager_sentiment']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 

  # Load Business Outlook
  df_data = query_capriole_metric("business_outlook")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"AMS": "active_manager_sentiment"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','business_outlook']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 

  # Load Equity Fear&Greed
  df_data = query_capriole_metric("equity_fear_greed")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"FearGreed": "equity_fear_greed"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','equity_fear_greed']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Equity Premium
  df_data = query_capriole_metric("equity_premium")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"AMS": "active_manager_sentiment"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','equity_premium']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Net Liquidity
  """df_data = query_capriole_metric("net_liquidity")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"AMS": "active_manager_sentiment"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','m2_yoy_less_rates']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) """

  # Load  Gold Stocks ratio
  df_data = query_capriole_metric("gold_stocks_ratio")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"AMS": "active_manager_sentiment"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','gsr']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 

  # Load Insider Trades
  df_data = query_capriole_metric("insider_trades")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"normalized": "insider_trades"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','insider_trades']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Market Breadth
  df_data = query_capriole_metric("market_breadth")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"breadth20": "market_breadth"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','market_breadth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load S&P Put Call Ratio
  df_data = query_capriole_metric("sp_put_call")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"NPCR": "sp_pcr"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','sp_pcr']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load US Liquidity
  df_data = query_capriole_metric("us_liquidity")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"liquidity_yoy": "us_liquidity_yoy"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','us_liquidity_yoy']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load USD Positioning
  df_data = query_capriole_metric("usd_positioning")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"net_usd_positioning_CFTC": "usd_positioning"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','usd_positioning']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Macro Ratios
  df_data = query_capriole_metric("macro_ratios")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"bbb": "bbb_credit_spread", "jnk_ief":"junk_treasuries"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','bbb_credit_spread','xly_xlp','como_spx','junk_treasuries']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Node Strategy
  df_data = query_capriole_metric("node_strategy")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"weight_target": "weight_node_strategy"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','weight_node_strategy']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Midas Gold Strategy
  df_data = query_capriole_metric("midas_gold")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"weight_target": "weight_midas_strategy"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','weight_midas_strategy']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Spectrum Strategy
  df_data = query_capriole_metric("spectrum")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"weight_target": "weight_spectrum_strategy"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','weight_spectrum_strategy']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Macro Index ETH
  df_data = query_capriole_metric("macro_index_eth")
  df_data = _force_col_to_number(df_data)
  df_data['macro_index_eth'] = df_data[['contraction', 'expansion', 'expansion_atr','recovery', 'slowdown']].max(axis=1)  
  print('DF Data: ', df_data.tail(), df_data.info())    
  #df_data = df_data.rename(columns={"weight_target": "weight_midas_strategy"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','macro_index_eth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Demand ETH
  df_data = query_capriole_metric("demand_eth")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"apparent_demand": "apparent_demand_eth"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','apparent_demand_eth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Heater ETH
  df_data = query_capriole_metric("heater_eth")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"heater": "heater_eth", "oi_pct_mcap":"oi_pct_mcap_eth"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','heater_eth', 'oi_pct_mcap_eth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 

  # Load Hodler Growth rate ETH
  df_data = query_capriole_metric("hodler_growth_rate_eth")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"active_more_2y_percent": "active_more_2y_pct_eth", "active_more_1y_percent":"active_more_1y_pct_eth", "active_more_6m_percent":"active_more_6m_pct_eth"})    
  df_capriole = pd.merge(df_capriole, df_data[['time','active_more_2y_pct_eth','active_more_1y_pct_eth','active_more_6m_pct_eth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())   

  # Load CDD Trend ETH
  df_data = query_capriole_metric("cdd_trend_eth")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"CDD_trend": "cdd_trend_eth"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','cdd_trend_eth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())

  # Load Alts Speculation Index
  df_data = query_capriole_metric("alts_speculation_index")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"Speculation Index": "speculation_index_eth"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','speculation_index_eth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info())  

  # Load Alts Crypto Breadth
  df_data = query_capriole_metric("alts_crypto_breadth")
  df_data = _force_col_to_number(df_data)
  #print('DF Data: ', df_data.tail(), df_data.info())    
  df_data = df_data.rename(columns={"breadth20": "crypto_breadth"})   
  df_capriole = pd.merge(df_capriole, df_data[['time','crypto_breadth']],on='time', how="outer")   
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 

  # Final clean up
  df_capriole = df_capriole.rename(columns={'price_usd_close': 'close'})
  df_capriole['date'] = pd.to_datetime(df_capriole['time'])
  df_capriole = df_capriole.drop('time', axis=1)      
  df_capriole = df_capriole[df_capriole["date"] >= pd.Timestamp("2016-01-01")].reset_index(drop=True)
  df_capriole['date'] = df_capriole['date'].dt.strftime('%Y-%m-%d')
  df_capriole = df_capriole.fillna(method='ffill')
  print('DF Capriole: ', df_capriole.tail(), df_capriole.info()) 
  df_capriole = df_capriole.replace([np.inf, -np.inf], 0)
  os.makedirs('data', exist_ok=True)
  df_capriole.to_csv('data/capriole_data.csv')
  
  # add imported data to database
  database.store_metric_table(df_capriole, 'capriole2')
  
  return
  

def query_capriole_metric(
    metric: str,
    *,
    end: Optional[int] = None,
    timeout: int = 30,
) -> pd.DataFrame:
    """
    Fetch data for a metric using its endpoint-bound signed URL from SIGNED_URLS.
    - Automatically parses the metric's signed URL (init_capriole_fetch).
    - Expands chart_data into rows and adds 'time' (YYYY-MM-DD).
    """
    key = _resolve_metric_key(metric)
    signed_url = SIGNED_URLS.get(key)
    if not signed_url:
        raise KeyError(
            f"No signed URL configured for metric '{metric}' (canonical '{key}'). "
            f"Add it to SIGNED_URLS."
        )

    # Parse the signed URL into an auth bundle
    auth = init_capriole_fetch(signed_url)

    slug = auth.get("bound_endpoint")
    if not slug:
        raise ValueError("Could not determine endpoint slug from the signed URL.")

    # Use 'end' from the signed URL unless explicitly provided
    end_param = end if end is not None else auth.get("default_end")
    if end_param is None:
        raise ValueError(
            "No 'end' found in the signed URL and none provided. "
            "Pass end=... (epoch ms) — but changing it may invalidate the signature."
        )

    query = {
        "end": int(end_param),
        "Policy": auth["Policy"],
        "Signature": auth["Signature"],
        "Key-Pair-Id": auth["Key-Pair-Id"],
    }
    # Properly URL-encode values (incl. +, /, = from base64)
    qs = urlencode(query, quote_via=quote)
    path = f"/v1/data/{slug}?{qs}"

    conn = http.client.HTTPSConnection(API_HOST, timeout=timeout)
    try:
        headers = auth.get("headers") or {}
        conn.request("GET", path, headers=headers)
        resp = conn.getresponse()
        body = resp.read()
        status = resp.status
    finally:
        conn.close()

    text = body.decode("utf-8", errors="replace")
    if status >= 400:
        raise RuntimeError(f"HTTP {status} from {path}: {text[:500]}")

    try:
        obj = json.loads(text)
    except json.JSONDecodeError:
        df = pd.DataFrame()
        df["time"] = pd.Series(dtype="object")
        return df

    df = _json_to_df(obj)
    df = _ensure_time_column(df)

    if "time" in df.columns and not df["time"].isna().all():
        df = df.sort_values("time").reset_index(drop=True)
        cols = ["time"] + [c for c in df.columns if c != "time"]
        df = df[cols]

    return df

# ----------------------------- Support functions -------------------------------------------------------------


def _resolve_metric_key(metric: str) -> str:
    """Map aliases to the canonical metric key present in SIGNED_URLS."""
    return _METRIC_ALIASES.get(metric, metric)

def _json_to_df(obj: Any) -> pd.DataFrame:
    """
    Normalize typical API shapes into a DataFrame:
    - dict with 'chart_data' -> expand into rows
    - list of dicts
    - list of [timestamp, value]
    - dict with 'data' or 'series'
    """
    if isinstance(obj, dict):
        if "chart_data" in obj and isinstance(obj["chart_data"], list):
            arr = obj["chart_data"]
            if arr and isinstance(arr[0], dict):
                return pd.DataFrame(arr)
            elif arr and isinstance(arr[0], (list, tuple)):
                ts = [x[0] if len(x) > 0 else np.nan for x in arr]
                val = [x[1] if len(x) > 1 else np.nan for x in arr]
                return pd.DataFrame({"timestamp": ts, "value": val})
            else:
                return pd.DataFrame({"chart_data": arr})
        # Other common containers
        for key in ("data", "values", "series", "payload", "result"):
            if key in obj:
                inner = obj[key]
                if isinstance(inner, list):
                    if inner and isinstance(inner[0], dict):
                        return pd.DataFrame(inner)
                    elif inner and isinstance(inner[0], (list, tuple)):
                        ts = [x[0] if len(x) > 0 else np.nan for x in inner]
                        val = [x[1] if len(x) > 1 else np.nan for x in inner]
                        return pd.DataFrame({"timestamp": ts, "value": val})
                return pd.json_normalize(inner)
        return pd.json_normalize(obj)

    if isinstance(obj, list):
        if not obj:
            return pd.DataFrame()
        if isinstance(obj[0], dict):
            return pd.DataFrame(obj)
        if isinstance(obj[0], (list, tuple)):
            ts = [x[0] if len(x) > 0 else np.nan for x in obj]
            val = [x[1] if len(x) > 1 else np.nan for x in obj]
            return pd.DataFrame({"timestamp": ts, "value": val})
        return pd.DataFrame({"value": obj})

    return pd.DataFrame()

def _ensure_time_column(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add a date-only 'time' column (YYYY-MM-DD) from a timestamp-like field.
    Tries common keys and handles seconds vs milliseconds vs ISO strings.
    """
    if df.empty:
        df["time"] = pd.Series(dtype="object")
        return df

    lower = {c.lower(): c for c in df.columns}
    candidates = ["timestamp", "time", "date", "t", "x", "ts"]
    ts_col = next((lower[c] for c in candidates if c in lower), None)

    if ts_col is None:
        num_cols = [c for c in df.columns if np.issubdtype(df[c].dtype, np.number)]
        ts_col = num_cols[0] if num_cols else (df.columns[0] if len(df.columns) else None)

    if ts_col is None:
        df["time"] = pd.Series(dtype="object")
        return df

    s = df[ts_col]
    if np.issubdtype(s.dtype, np.number):
        max_val = pd.to_numeric(s, errors="coerce").max()
        unit = "s" if (pd.isna(max_val) or max_val < 1e11) else "ms"
        dt = pd.to_datetime(s, unit=unit, errors="coerce", utc=True)
    else:
        dt = pd.to_datetime(s, errors="coerce", utc=True)

    df["time"] = dt.dt.tz_convert(None).dt.strftime("%Y-%m-%d")
    return df

def init_capriole_fetch(
    signed_url: str,
    *,
    referer: str = DEFAULT_REFERER,
    origin: str = DEFAULT_ORIGIN,
    user_agent: str = USER_AGENT,
) -> Dict[str, Any]:
    """
    Parse a working signed URL to extract Policy, Signature, Key-Pair-Id,
    the bound endpoint (slug), and a default 'end' if present.
    """
    if not signed_url:
        raise ValueError("Please provide a working signed URL for this metric.")
    u = urlparse(signed_url)
    path = u.path or ""
    bound_endpoint = path.split("/v1/data/", 1)[-1] if "/v1/data/" in path else None

    qs = parse_qs(u.query)
    def first(name: str) -> Optional[str]:
        v = qs.get(name)
        return v[0] if v else None

    policy = first("Policy")
    signature = first("Signature")
    key_pair_id = first("Key-Pair-Id")
    default_end = first("end")

    if not (policy and signature and key_pair_id):
        raise ValueError("Signed URL missing one of Policy, Signature, or Key-Pair-Id.")

    auth = {
        "Policy": policy,
        "Signature": signature,
        "Key-Pair-Id": key_pair_id,
        "default_end": int(default_end) if default_end and default_end.isdigit() else default_end,
        "bound_endpoint": bound_endpoint,
        "headers": {
            "Accept": "*/*",
            "Accept-Language": "en,de-DE;q=0.9,de;q=0.8,en-US;q=0.7",
            "Origin": origin,
            "Referer": referer,
            "User-Agent": user_agent,
        },
    }
    return auth
